Repository G1-Group/TCB.DevKings, pull requests merged in 2023-08, with the labels that each got.

#90 bajarildi
  TCBApp/TCBApp/TelegramBot/TelegramBot.cs
Labels: finished

#87 implemented session manager service
  TCBApp/TCBApp/Model/Session.cs
  TCBApp/TCBApp/Services/DBServices/UserDataService.cs
  TCBApp/TCBApp/TelegramBot/SimpleSessionManager/ISessionManager.cs
  TCBApp/TCBApp/TelegramBot/SimpleSessionManager/SessionManager.cs
Labels: finished

#91 ControllerContext ready to use
  TCBApp/TCBApp/TelegramBot/ControllerContext.cs
Labels: accepted

#97 Golibjon/88 set column name of the property with description attribute as follow below
  TCBApp/TCBApp/Model/BoardModel.cs
  TCBApp/TCBApp/Model/ChatModel.cs
  TCBApp/TCBApp/Model/Client.cs
  TCBApp/TCBApp/Model/Message.cs
  TCBApp/TCBApp/Model/User.cs
  TCBApp/TCBApp/Model/UserRegstration.cs
Labels: rejected

#99 created ControllerBase and HandlerAction
  TCBApp/TCBApp/ControllerBase.cs
Labels: finished

#98 To List in SessionManager
  TCBApp/TCBApp/TelegramBot/SimpleSessionManager/SessionManager.cs
Labels: finished

#102 EpdateHandler list created
  TCBApp/TCBApp/Program.cs
  TCBApp/TCBApp/TelegramBot/TelegramBot.cs
Labels: finished

#101 Refactored
  TCBApp/TCBApp/TelegramBot/TelegramBot.cs
Labels: finished

#106 ClientService ready to check
  TCBApp/TCBApp/Services/ClientService.cs
  TCBApp/TCBApp/Services/DBServices/ClientDataService.cs
  TCBApp/TCBApp/Services/Interface/IClientService.cs
Labels: finished

#113 AuthController Finished To use
  TCBApp/TCBApp/TelegramBot/Controllers/AuthController.cs
Labels: finished

#114 BoardController is implemented;
  TCBApp/TCBApp/Services/BoardService.cs
  TCBApp/TCBApp/Services/DBServices/MessageDataService.cs
  TCBApp/TCBApp/Services/Interface/IBoardInterface.cs
  TCBApp/TCBApp/TelegramBot/Controllers/BoardController.cs
Labels: finished

#118 ClientController finished
  TCBApp/TCBApp/TelegramBot/Controllers/AuthController.cs
  TCBApp/TCBApp/TelegramBot/Controllers/ClientController.cs
Labels: finished

#119 Bug Fixed
  TCBApp/TCBApp/Services/ClientService.cs
  TCBApp/TCBApp/Services/DBServices/ClientDataService.cs
Labels: accepted

#124 Handlers pipeline implemented
  TCBApp/TCBApp/Model/Session.cs
  TCBApp/TCBApp/TelegramBot/SimpleSessionManager/SessionManager.cs
  TCBApp/TCBApp/TelegramBot/TelegramBot.cs
Labels: finished

#136 AuthControllerUpdated
  TCBApp/TCBApp/Program.cs
  TCBApp/TCBApp/Services/BoardService.cs
  TCBApp/TCBApp/TelegramBot/Controllers/AuthController.cs
Labels: finished

#137 Authorization and Authentication implemented
  TCBApp/TCBApp/Configurations/Settings.cs
  TCBApp/TCBApp/DBConnection/DBConnection.cs
  TCBApp/TCBApp/Model/Entity/BoardModel.cs
  TCBApp/TCBApp/Model/Entity/ChatModel.cs
  TCBApp/TCBApp/Model/Entity/Client.cs
  TCBApp/TCBApp/Model/Entity/Enum/BoardStatus.cs
  TCBApp/TCBApp/Model/Entity/Enum/ChatState.cs
  TCBApp/TCBApp/Model/Entity/Enum/ClientStatus.cs
  TCBApp/TCBApp/Model/Entity/Enum/MessageStatus.cs
  TCBApp/TCBApp/Model/Entity/Enum/MessageType.cs
  TCBApp/TCBApp/Model/Entity/Message.cs
  TCBApp/TCBApp/Model/Entity/Session.cs
  TCBApp/TCBApp/Model/Entity/User.cs
  TCBApp/TCBApp/Model/Session.cs
  TCBApp/TCBApp/Model/UserRegstration.cs
  TCBApp/TCBApp/Model/ViewModel/UserLoginModel.cs
  TCBApp/TCBApp/Model/ViewModel/UserRegistrationModel.cs
  TCBApp/TCBApp/Program.cs
  TCBApp/TCBApp/Services/AuthService.cs
  TCBApp/TCBApp/Services/BoardService.cs
  TCBApp/TCBApp/Services/ClientService.cs
  TCBApp/TCBApp/Services/ConversationService.cs
  TCBApp/TCBApp/Services/DBServices/ClientDataService.cs
  TCBApp/TCBApp/Services/DBServices/DataProvider.cs
  TCBApp/TCBApp/Services/DBServices/UserDataService.cs
  TCBApp/TCBApp/Services/Interface/IAuthInterface.cs
  TCBApp/TCBApp/TCBApp.csproj
  TCBApp/TCBApp/TelegramBot/Context/Extensions/ContextExtensions.cs
  TCBApp/TCBApp/TelegramBot/ControllerManager/ControllerManager.cs
  TCBApp/TCBApp/TelegramBot/Controllers/AuthController.cs
  TCBApp/TCBApp/TelegramBot/Controllers/ControllerBase.cs
  TCBApp/TCBApp/TelegramBot/Controllers/HomeController.cs
  TCBApp/TCBApp/TelegramBot/SimpleSessionManager/SessionManager.cs
  TCBApp/TCBApp/TelegramBot/TelegramBot.cs
Labels: finished

#140 Abdumannon/dashboard board models implemented
  TCBApp/TCBApp/Model/Entity/Enum/BoardStatus.cs
  TCBApp/TCBApp/Model/SessionModel/BoardSessionModel.cs
  TCBApp/TCBApp/Model/SessionModel/Session.cs
  TCBApp/TCBApp/Services/BoardService.cs
  TCBApp/TCBApp/Services/DBServices/BoardDataService.cs
  TCBApp/TCBApp/Services/DBServices/UserDataService.cs
  TCBApp/TCBApp/TCBApp.csproj
  TCBApp/TCBApp/TelegramBot/Context/Extensions/ContextExtensions.cs
  TCBApp/TCBApp/TelegramBot/Context/UserControllerContext.cs
  TCBApp/TCBApp/TelegramBot/ControllerManager/ControllerManager.cs
  TCBApp/TCBApp/TelegramBot/Controllers/AuthController.cs
  TCBApp/TCBApp/TelegramBot/Controllers/BoardController.cs
  TCBApp/TCBApp/TelegramBot/Controllers/ClientDashboardController.cs
  TCBApp/TCBApp/TelegramBot/Controllers/ControllerBase.cs
  TCBApp/TCBApp/TelegramBot/Controllers/HomeController.cs
  TCBApp/TCBApp/TelegramBot/Extensions/ContextExtensions.cs
  TCBApp/TCBApp/TelegramBot/Extensions/KeyboardButtonExtensions.cs
  TCBApp/TCBApp/TelegramBot/SimpleSessionManager/SessionManager.cs
  TCBApp/TCBApp/TelegramBot/TelegramBot.cs
Labels: finished

#141 changed
  TCBApp/TCBApp/Configurations/Settings.cs
  TCBApp/TCBApp/TelegramBot/Controllers/AuthController.cs
  TCBApp/TCBApp/TelegramBot/Controllers/BoardController.cs
  TCBApp/TCBApp/TelegramBot/Controllers/ClientDashboardController.cs
Labels: accepted

#145 Added ClientInfoController
  TCBApp/TCBApp/Services/ClientService.cs
  TCBApp/TCBApp/Services/Interface/IClientService.cs
  TCBApp/TCBApp/TelegramBot/ControllerManager/ControllerManager.cs
  TCBApp/TCBApp/TelegramBot/Controllers/AuthController.cs
  TCBApp/TCBApp/TelegramBot/Controllers/BoardController.cs
  TCBApp/TCBApp/TelegramBot/Controllers/ClientDashboardController.cs
  TCBApp/TCBApp/TelegramBot/Controllers/ClientInfoController.cs
  TCBApp/TCBApp/TelegramBot/Controllers/ConversationsController.cs
  TCBApp/TCBApp/TelegramBot/Controllers/SettingsController.cs
  TCBApp/TCBApp/TelegramBot/Extensions/ContextExtensions.cs
  TCBApp/TCBApp/TelegramBot/Extensions/KeyboardButtonExtensions.cs
Labels: finished

#146 changed
  TCBApp/TCBApp/Model/SessionModel/BoardSessionModel.cs
  TCBApp/TCBApp/Services/MessageService.cs
  TCBApp/TCBApp/TCBApp.csproj
  TCBApp/TCBApp/TelegramBot/ControllerManager/ControllerManager.cs
  TCBApp/TCBApp/TelegramBot/Controllers/AdminController.cs
  TCBApp/TCBApp/TelegramBot/Controllers/AuthController.cs
  TCBApp/TCBApp/TelegramBot/Controllers/BoardController.cs
  TCBApp/TCBApp/TelegramBot/Controllers/ConversationController.cs
  TCBApp/TCBApp/TelegramBot/Extensions/KeyboardButtonExtensions.cs
Labels: new

#149 Golibjon/board controller
  TCBApp/TCBApp/Services/DBServices/MessageDataService.cs
  TCBApp/TCBApp/Services/MessageService.cs
  TCBApp/TCBApp/TelegramBot/ControllerManager/ControllerManager.cs
  TCBApp/TCBApp/TelegramBot/Controllers/BoardController.cs
Labels: finished

#151 Ef core implemented
  TCBApp/TCBApp/Configurations/Settings.cs
  TCBApp/TCBApp/Model/Entity/BoardModel.cs
  TCBApp/TCBApp/Model/Entity/ChatModel.cs
  TCBApp/TCBApp/Model/Entity/Client.cs
  TCBApp/TCBApp/Model/Entity/Message.cs
  TCBApp/TCBApp/Model/Entity/ModelBase.cs
  TCBApp/TCBApp/Model/Entity/User.cs
  TCBApp/TCBApp/Model/ViewModel/SendMessageToBoardViewModel.cs
  TCBApp/TCBApp/Program.cs
  TCBApp/TCBApp/Services/AuthService.cs
  TCBApp/TCBApp/Services/BoardService.cs
  TCBApp/TCBApp/Services/ClientService.cs
  TCBApp/TCBApp/Services/ConversationService.cs
  TCBApp/TCBApp/Services/DBServices/BoardDataService.cs
  TCBApp/TCBApp/Services/DBServices/ClientDataService.cs
  TCBApp/TCBApp/Services/DBServices/ConversationDataService.cs
  TCBApp/TCBApp/Services/DBServices/DataProvider.cs
  TCBApp/TCBApp/Services/DBServices/MessageDataService.cs
  TCBApp/TCBApp/Services/DBServices/UserDataService.cs
  TCBApp/TCBApp/Services/DataContexts/DataContext.cs
  TCBApp/TCBApp/Services/DataService/BoardDataService.cs
  TCBApp/TCBApp/Services/DataService/ClientDataService.cs
  TCBApp/TCBApp/Services/DataService/ConversationDataService.cs
  TCBApp/TCBApp/Services/DataService/DataServiceBase.cs
  TCBApp/TCBApp/Services/DataService/IUserDataService.cs
  TCBApp/TCBApp/Services/DataService/MessageDataService.cs
  TCBApp/TCBApp/Services/DataService/UserDataService.cs
  TCBApp/TCBApp/Services/Interface/IAuthInterface.cs
  TCBApp/TCBApp/Services/Interface/IAuthService.cs
  TCBApp/TCBApp/Services/Interface/IBoardInterface.cs
  TCBApp/TCBApp/Services/Interface/IBoardService.cs
  TCBApp/TCBApp/Services/Interface/IClientService.cs
  TCBApp/TCBApp/Services/Interface/IConversationInterface.cs
  TCBApp/TCBApp/Services/Interface/IConversationService.cs
  TCBApp/TCBApp/Services/Interface/IDataServiceBase.cs
  TCBApp/TCBApp/Services/Interface/IMessageService.cs
  TCBApp/TCBApp/Services/MessageService.cs
  TCBApp/TCBApp/TCBApp.csproj
  TCBApp/TCBApp/TelegramBot/ControllerManager/ControllerManager.cs
  TCBApp/TCBApp/TelegramBot/Controllers/AuthController.cs
  TCBApp/TCBApp/TelegramBot/Controllers/BoardController.cs
  TCBApp/TCBApp/TelegramBot/Controllers/ClientDashboardController.cs
  TCBApp/TCBApp/TelegramBot/Controllers/ClientInfoController.cs
  TCBApp/TCBApp/TelegramBot/Controllers/ConversationsController.cs
  TCBApp/TCBApp/TelegramBot/Controllers/SettingsController.cs
  TCBApp/TCBApp/TelegramBot/Extensions/ContextExtensions.cs
  TCBApp/TCBApp/TelegramBot/SimpleSessionManager/SessionManager.cs
  TCBApp/TCBApp/TelegramBot/TelegramBot.cs
Labels: finished, important!

#154 Mistake is corrected
  TCBApp/TCBApp/Services/BoardService.cs
  TCBApp/TCBApp/Services/MessageService.cs
  TCBApp/TCBApp/TelegramBot/Controllers/BoardController.cs
Labels: finished

#156 Conversation messages savead to database
  TCBApp/TCBApp/Configurations/Settings.cs
  TCBApp/TCBApp/Model/ViewModel/SendMessageToConversationViewModel.cs
  TCBApp/TCBApp/Services/DataService/DataServiceBase.cs
  TCBApp/TCBApp/Services/DataService/MessageDataService.cs
  TCBApp/TCBApp/Services/Interface/IMessageService.cs
  TCBApp/TCBApp/Services/MessageService.cs
  TCBApp/TCBApp/TelegramBot/ControllerManager/ControllerManager.cs
  TCBApp/TCBApp/TelegramBot/Controllers/ConversationsController.cs
Labels: accepted

#157 Board Inline KeyboardButtonExtensions
  TCBApp/TCBApp/TelegramBot/Controllers/BoardController.cs
  TCBApp/TCBApp/TelegramBot/Extensions/KeyboardButtonExtensions.cs
Labels: finished

#158 bug fixed
  TCBApp/TCBApp/TelegramBot/Extensions/KeyboardButtonExtensions.cs
Labels: finished

#160 Boarding finding improved
  TCBApp/TCBApp/Configurations/Settings.cs
  TCBApp/TCBApp/Migrations/DataContextModelSnapshot.cs
  TCBApp/TCBApp/Model/Entity/User.cs
  TCBApp/TCBApp/Model/SessionModel/InlineResultModel.cs
  TCBApp/TCBApp/Model/SessionModel/Session.cs
  TCBApp/TCBApp/Services/AuthService.cs
  TCBApp/TCBApp/TelegramBot/ControllerManager/ControllerManager.cs
  TCBApp/TCBApp/TelegramBot/Controllers/BoardController.cs
  TCBApp/TCBApp/TelegramBot/Controllers/ClientDashboardController.cs
  TCBApp/TCBApp/TelegramBot/Controllers/ControllerBase.cs
  TCBApp/TCBApp/TelegramBot/Extensions/ContextExtensions.cs
  TCBApp/TCBApp/TelegramBot/Extensions/KeyboardButtonExtensions.cs
  TCBApp/TCBApp/TelegramBot/TelegramBot.cs
Labels: finished, important!

#179 Create HttpContext
  TCBApp/TCBApp.WebApi/HttpContext.cs
Labels: finished

#202 Jamolxon/implment data from attribute
  TCBApp/TCBApp.WebApi/Attribute/FromData.cs
  TCBApp/TCBApp.WebApi/Attribute/FromHeader.cs
  TCBApp/TCBApp.WebApi/Attribute/FromQuery.cs
Labels: finished

#191 write httprequestbody to given type converter as generic extension method
  TCBApp/TCBApp.WebApi/Extensions/RequestExtension.cs
  TCBApp/TCBApp.WebApi/Extensions/ResponseExtensions.cs
Labels: finished
